src/objects/Lead_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Raw_Data__c</fullName>
        <label>Raw Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>hasError__c</fullName>
        <defaultValue>false</defaultValue>
        <label>hasError</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Normalized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Normalized</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Staging</label>
    <nameField>
        <displayFormat>LS-{0}</displayFormat>
        <label>Lead Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Webservice_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Access_Key__c</fullName>
        <label>Access Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Webservice Settings</label>
</CustomObject>

src/classes/LeadStagingWebserviceTest.cls
@isTest
public with sharing class LeadStagingWebserviceTest {
	

	/*
	*  @Description : Method used to test the json webservice
	*/
	static testMethod void test_JSONWebservice(){
		Test.startTest();

		// Create accessKey
		Webservice_Settings__c webserviceSettings = new Webservice_Settings__c(Access_Key__c='abc123');
		insert webserviceSettings;

		// Set the values in the Rest context
		RestRequest req = new RestRequest();
		req.requestURI = '/services/apexrest/leadstaging';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueof(JSONParserTest.jsonString);
		req.addHeader('Content-Type','application/json');
		req.addParameter('access_key','abc123');
		RestContext.request = req;

		// Call the method
		LeadStagingWebService.createLeadStaging();

		// Check if lead statging record created successfully
		Lead_Staging__c leadStaging = [SELECT hasError__c, is_Normalized__c, Error_Message__c, Raw_Data__c FROM Lead_Staging__c LIMIT 1];

		System.assertNotEquals(null,leadStaging);
		System.assertEquals(false,leadStaging.hasError__c); 
		System.assertNotEquals(false,leadStaging.is_Normalized__c);
		System.assertEquals(null,leadStaging.Error_Message__c);
		System.assert(leadStaging.Raw_Data__c != '');
		Test.stopTest();
	}


	/*
	*  @Description : Method used to test the xml webservice
	*/
	static testMethod void test_XMLWebservice(){
		Test.startTest();

		// Create accessKey
		Webservice_Settings__c webserviceSettings = new Webservice_Settings__c(Access_Key__c='abc123');
		insert webserviceSettings;

		// Set the values in the Rest context
		RestRequest req = new RestRequest();
		req.requestURI = '/services/apexrest/leadstaging';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueof(XMLParserTest.xmlString);
		req.addHeader('Content-Type','application/xml');
		req.addParameter('access_key','abc123');
		RestContext.request = req;

		// Call the method
		LeadStagingWebService.createLeadStaging();

		// Check if lead statging record created successfully
		Lead_Staging__c leadStaging = [SELECT hasError__c, is_Normalized__c, Error_Message__c, Raw_Data__c FROM Lead_Staging__c LIMIT 1];

		System.assertNotEquals(null,leadStaging);
		System.assertEquals(false,leadStaging.hasError__c); 
		System.assertNotEquals(false,leadStaging.is_Normalized__c);
		System.assertEquals(null,leadStaging.Error_Message__c);
		System.assert(leadStaging.Raw_Data__c != '');
		Test.stopTest();
	}
}